env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'import'
rules: {
    '@typescript-eslint/no-unused-vars': 'error', # to enforce using type for object type definitions, can be type or interface
    'import/extensions': 0,
    'import/no-unresolved': 0,
  }
settings:
  {
    'import/resolver':
      {
        node:
          {
            extensions: ['.js', '.jsx', '.ts', '.tsx'],
            moduleDirectory: ['node_modules', 'src/'],
          },
      },
  }
